blob.server.port: 6124
fs.gs.retry.rpc-timeout-multiplier: 1.5
classloader.resolve-order: parent-first
gs.filesink.entropy.enabled: true
jobmanager.rpc.address: jobmanager
gs.writer.temporary.bucket.name: your-temp-bucket
fs.gs.retry.total-timeout: 60000
query.server.port: 6125
fs.gs.http.connect-timeout: 20000
taskmanager.memory.flink.size: 2048m
fs.gs.retry.max-attempt: 5
taskmanager.memory.managed.size: 512m
parallelism.default: 2
taskmanager.numberOfTaskSlots: 4
taskmanager.memory.task.heap.size: 1024m
fs.gs.http.read-timeout: 20000
jobmanager.memory.heap.size: 1024m
jobmanager.memory.flink.size: 1280m
